PackageIdentifier: DanyalJam.DTools
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: DanyalJam
PackageName: DTools
License: Proprietary
ShortDescription: Process PDFs, images, and text locally in your browser.
PackageUrl: https://github.com/danyaljam/DANTOOLS
ManifestType: defaultLocale
ManifestVersion: 1.6.0