PackageIdentifier: DanyalJam.DTools
PackageVersion: 1.0.0
InstallerLocale: en-US
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Scope: user
InstallModes:
  - interactive
UpgradeBehavior: uninstallPrevious
Dependencies:
  PackageDependencies:
    - PackageIdentifier: OpenJS.NodeJS.LTS
      MinimumVersion: 22.13.0
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/danyaljam/DANTOOLS/releases/download/v1.0.0/dtools-1.0.0.exe
    InstallerSha256: 99741ef9fe076a9efa23f039645a5dc2b234023cf7666e7c08f6c45d3e582768
    Commands:
      - dtools
ManifestType: installer
ManifestVersion: 1.6.0