PackageIdentifier: DanyalJam.DTools
PackageVersion: 1.0.0
InstallerLocale: en-US
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Scope: user
InstallModes:
  - interactive
UpgradeBehavior: uninstallPrevious
Dependencies:
  PackageDependencies:
    - PackageIdentifier: OpenJS.NodeJS.LTS
      MinimumVersion: 22.13.0
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/danyaljam/DANTOOLS/releases/download/v1.0.0/dtools-1.0.0.exe
    InstallerSha256: 45215c4eea2adc231f239d42cce2a4c62c43ad4138290fbc631451e5096ea01f
    Commands:
      - dtools
ManifestType: installer
ManifestVersion: 1.6.0